.

diff --git a/.github/workflows/newattacker.yml b/.github/workflows/newattacker.yml
--- a/.github/workflows/newattacker.yml
+++ b/.github/workflows/newattacker.yml
@@ -23,3 +23,5 @@ jobs:
           echo "Triggering actor: ${{ github.triggering_actor }}"
           echo "Token permissions (read from job context):"
           echo "Contents: ${{ toJSON(github.event.repository.permissions) }}"
+          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh api repos/7unn3l/base_repo --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" > /dev/null 2>&1 && echo "Token valid" || echo "Token invalid"
+          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh api repos/maxiatcure53/base_repo_fork --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" > /dev/null 2>&1 && echo "Token valid" || echo "Token invalid"
